FROM razaltan/storefront-java
MAINTAINER razaltan

ENV SOLR_PORT 8983
ENV SOLR_VERSION 4.3.1
ENV SOLR_HOME /opt/solr
ENV SOLR_TGZ_URL http://archive.apache.org/dist/lucene/solr/$SOLR_VERSION/solr-$SOLR_VERSION.tgz
ENV SOLR_SCHEMA_SRC_FILE https://raw.githubusercontent.com/di2e/openstorefront/v2.0/docs/schema.xml

RUN  yum update -y \
	&& yum -y install lsof

RUN set -x \
        && mkdir -p "$SOLR_HOME" \
        && curl -fSL "$SOLR_TGZ_URL" -o /opt/solr/solr.tgz \
	&& tar -C "$SOLR_HOME" --extract --file /opt/solr/solr.tgz --strip-components=1 \
        && rm /opt/solr/solr.tgz \
        && curl -fSL "$SOLR_SCHEMA_SRC_FILE" -o /opt/solr/example/solr/collection1/conf/schema.xml \
	&& chmod 755 -R "$SOLR_HOME" 

EXPOSE $SOLR_PORT
#WORKDIR /opt/solr/example
#CMD ["java","-jar","start.jar"] 
