#!/bin/sh
if [ "$IMAGE_NAME" = "latest" ]; then
	BUILD_WAR="TRUE"
	WAR_VERSION="x" #WAR_VERSION not used if built from source
	echo "building latest not yet supported"
	exit
else
        BUILD_WAR="FALSE"
	arrayImageParts=
	WAR_VERSION="${IMAGE_NAME#*-}"
fi

docker build --build-arg BUILD=$BUILD_WAR --build-arg STOREFRONT_VERSION=$WAR_VERSION -t $IMAGE_NAME .
